# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-03 15:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asociacion', '0002_auto_20161028_1709'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni_representante', models.CharField(blank=True, max_length=8, null=True)),
                ('fecha', models.DateTimeField()),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asociacion.SocioLote')),
            ],
            options={
                'verbose_name': 'Asistencia',
                'verbose_name_plural': 'Asistencias',
            },
        ),
    ]
