# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-03 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_auto_20161103_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='descripcion',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
