# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-03 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0004_inasistencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inasistencia',
            name='monto',
            field=models.CharField(choices=[('10', '10'), ('20', '20'), ('50', '50')], max_length=2),
        ),
    ]
