# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-25 01:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auths', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conyuge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domicilio', models.CharField(blank=True, max_length=300, null=True)),
                ('procedencia', models.CharField(blank=True, max_length=50, null=True)),
                ('celular', models.CharField(blank=True, max_length=30, null=True)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('residencia_juliaca', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], max_length=2)),
                ('is_adventista', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], max_length=2)),
                ('conyuge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auths.Person')),
            ],
            options={
                'verbose_name': 'Conyuge',
                'verbose_name_plural': 'Conyuges',
            },
        ),
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_civil', models.CharField(blank=True, choices=[('Soltero', 'Soltero'), ('Casado', 'Casado'), ('Viudo', 'Viudo'), ('Divorsiado', 'Divorsiado')], max_length=20, null=True)),
                ('domicilio', models.CharField(blank=True, max_length=300, null=True)),
                ('procedencia', models.CharField(blank=True, max_length=50, null=True)),
                ('celular', models.CharField(blank=True, max_length=30, null=True)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('residencia_juliaca', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], max_length=2)),
                ('is_adventista', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], max_length=2)),
                ('conyuge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='socio.Conyuge')),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auths.Person')),
            ],
            options={
                'verbose_name': 'Socio',
                'verbose_name_plural': 'Socios',
            },
        ),
    ]
