# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-28 03:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sociolote',
            name='area_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
