# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-25 04:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socio', '0002_auto_20161024_2315'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conyuge',
            old_name='person',
            new_name='persona',
        ),
        migrations.RenameField(
            model_name='socio',
            old_name='person',
            new_name='persona',
        ),
    ]
