# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-25 04:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socio', '0005_auto_20161024_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='conyuge',
            name='email',
            field=models.EmailField(default=0, max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='socio',
            name='email',
            field=models.EmailField(default=0, max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
