# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-25 04:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socio', '0006_auto_20161024_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socio',
            name='estado_civil',
            field=models.CharField(choices=[('Soltero', 'Soltero'), ('Casado', 'Casado'), ('Viudo', 'Viudo'), ('Divorsiado', 'Divorsiado')], default=0, max_length=20),
            preserve_default=False,
        ),
    ]
