# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-25 05:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socio', '0009_auto_20161025_0036'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
