# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-25 06:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socio', '0011_socio_conyu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socio',
            name='conyu',
        ),
        migrations.AlterField(
            model_name='socio',
            name='conyuge',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='socio', to='socio.Socio'),
        ),
    ]
