# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-25 06:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socio', '0012_auto_20161025_0125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conyuge',
            name='email',
        ),
        migrations.RemoveField(
            model_name='conyuge',
            name='persona',
        ),
    ]
