# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-16 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default=2, max_length=40),
            preserve_default=False,
        ),
    ]
