# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-25 20:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='documento',
            field=models.CharField(default=0, help_text='documento nacional de identidad', max_length=8, unique=True, verbose_name='Identificacion'),
            preserve_default=False,
        ),
    ]
