# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-28 11:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DocumentoIdentidad',
        ),
    ]
