# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-25 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0002_person_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentoidentidad',
            name='documento',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
