# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-16 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0002_person_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(default=2, help_text='apellido paterno', max_length=50, verbose_name='Last name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='mother_last_name',
            field=models.CharField(help_text='apellido materno', max_length=50, verbose_name="Mother's last name"),
        ),
        migrations.AlterField(
            model_name='person',
            name='national_id_doc',
            field=models.CharField(default=1, help_text='documento nacional de identidad', max_length=8, unique=True, verbose_name='DNI'),
            preserve_default=False,
        ),
    ]
