# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-27 02:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asociacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='area_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='area total'),
        ),
        migrations.AddField(
            model_name='lote',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
