# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-20 22:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asociacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asociacion',
            options={'verbose_name': 'asociacion', 'verbose_name_plural': 'asociaciones'},
        ),
    ]
