# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-20 01:58
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('asociacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo_lote', models.CharField(max_length=2, unique=True, verbose_name='arreglo lote')),
                ('area_total', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='area total')),
                ('area_construida', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='area construida')),
                ('area_sin_construir', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='area sin construir')),
                ('observaciones', models.TextField(max_length=500)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Lote',
                'verbose_name_plural': 'Lotes',
            },
        ),
    ]
