# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-26 12:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asociacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relacionmanzana',
            name='lote',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='asociacion.Lote'),
        ),
        migrations.AlterField(
            model_name='relacionmanzana',
            name='manzana',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asociacion.Manzana'),
        ),
    ]
