# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-04 11:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asociacion', '0001_initial'),
        ('auths', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='socio',
            name='persona',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auths.Person'),
        ),
        migrations.AddField(
            model_name='lote',
            name='manzana',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asociacion.Manzana'),
        ),
        migrations.AddField(
            model_name='informacionlote',
            name='lote',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='asociacion.Lote'),
        ),
        migrations.AddField(
            model_name='asociacion',
            name='cuenta_banco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asociacion.CuentaBanco'),
        ),
    ]
