# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-28 03:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asociacion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lote',
            name='area_total',
        ),
    ]
