# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-06 22:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asociacion', '0002_auto_20161106_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banco',
            name='banco',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='tipocuenta',
            name='tipo_cuenta',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
