# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-27 22:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asociacion', '0002_auto_20161127_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asociacion',
            name='cuenta_banco',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='asociaciones', to='asociacion.CuentaBanco'),
        ),
    ]
