# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-20 02:02
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('asociacion', '0002_lote'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manzana',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('manzana', models.CharField(max_length=3, unique=True, verbose_name='manzana')),
                ('numero_lotes', models.PositiveSmallIntegerField(default=1, verbose_name='numero lotes')),
            ],
            options={
                'verbose_name': 'Manzana',
                'verbose_name_plural': 'Manzanas',
            },
        ),
    ]
