# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-04 06:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asociacion', '0003_auto_20161103_2350'),
    ]

    operations = [
        migrations.AddField(
            model_name='sociolote',
            name='estado_inmueble',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
