# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-06 22:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asociacion', '0003_auto_20161106_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentabanco',
            name='tipo_cuenta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asociacion.TipoCuenta'),
        ),
    ]
