# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-04 06:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asociacion', '0004_sociolote_estado_inmueble'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociolote',
            name='estado_inmueble',
            field=models.CharField(blank=True, choices=[('Terreno sin construir', 'Terreno sin construir'), ('Terreno con cerco perimetrico', 'Terreno con cerco perimetrico'), ('Inmueble parcialmente construido', 'Inmueble parcialmente construido'), ('Inmueble construido - primera planta', 'Inmueble construido - primera planta'), ('Inmueble construido - segunda planta', 'Inmueble construido - segunda planta'), ('Inmueble construido - más de dos plantas', 'Inmueble construido - más de dos plantas')], max_length=5, null=True),
        ),
    ]
