# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-04 06:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asociacion', '0005_auto_20161104_0136'),
    ]

    operations = [
        migrations.AddField(
            model_name='sociolote',
            name='observaciones',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
