# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-06 22:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asociacion', '0005_auto_20161106_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentabanco',
            name='entidad_bancaria',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='cuentabanco',
            name='tipo_cuenta',
            field=models.CharField(max_length=50),
        ),
    ]
