# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-06 22:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asociacion', '0007_auto_20161106_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentabanco',
            name='entidad_bancaria',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
