# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-04 06:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cobranza', '0002_auto_20161104_0101'),
    ]

    operations = [
        migrations.CreateModel(
            name='Debe',
            fields=[
                ('codigo_deb', models.AutoField(primary_key=True, serialize=False)),
                ('glosa_debe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cobranza.RubroCobranza')),
            ],
            options={
                'verbose_name': 'Debe',
                'verbose_name_plural': 'Lista de DEBE',
            },
        ),
        migrations.CreateModel(
            name='Haber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Haber',
                'verbose_name_plural': 'Habers',
            },
        ),
    ]
