# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-04 06:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='debe',
            options={'verbose_name': 'DEBE', 'verbose_name_plural': 'DEBE'},
        ),
        migrations.AlterModelOptions(
            name='haber',
            options={'verbose_name': 'HABER', 'verbose_name_plural': 'HABER'},
        ),
    ]
