# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-21 01:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RubroCobranza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto_cobranza', models.CharField(max_length=80, unique=True)),
                ('importe', models.DecimalField(decimal_places=2, max_digits=5)),
                ('mora', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('detalle', models.TextField(max_length=500)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
            ],
            options={
                'verbose_name': 'RubroCobranza',
                'verbose_name_plural': 'RubroCobranzas',
            },
        ),
    ]
