# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-04 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobranza', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuota',
            name='cuota',
            field=models.CharField(max_length=5),
        ),
    ]
