# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-27 15:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cobranza', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MontoCuota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('rub_cobr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cobranza.RubroCobranza')),
            ],
            options={
                'verbose_name_plural': 'MontoCuotas',
                'verbose_name': 'MontoCuota',
            },
        ),
    ]
