# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-04 06:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cobranza', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debe',
            name='glosa_debe',
        ),
        migrations.DeleteModel(
            name='Debe',
        ),
    ]
