# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-28 02:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cobranza', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='montocuota',
            name='lote',
        ),
    ]
