# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-04 06:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cobranza', '0002_auto_20161104_0101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='validarpago',
            name='cuenta_banco',
        ),
        migrations.RemoveField(
            model_name='validarpago',
            name='cuota_socio',
        ),
        migrations.DeleteModel(
            name='ValidarPago',
        ),
    ]
