# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-28 06:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cobranza', '0002_auto_20161028_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuota',
            name='socio_lote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asociacion.InformacionLote'),
        ),
    ]
