# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-26 15:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cobranza', '0002_auto_20161026_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rubrocobranza',
            name='concepto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cobranza.ConceptoCobranza'),
        ),
    ]
