# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-04 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobranza', '0002_auto_20161104_0737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuota',
            name='cuota',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
