# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-28 06:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cobranza', '0003_auto_20161028_0113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cuota',
            old_name='socio_lote',
            new_name='lote',
        ),
    ]
