# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-28 06:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socio', '0002_auto_20161028_0131'),
        ('cobranza', '0004_auto_20161028_0127'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuotaSocio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuota', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cobranza.Cuota')),
                ('socio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='socio.SocioLote')),
            ],
            options={
                'verbose_name_plural': 'CuotaSocios',
                'verbose_name': 'CuotaSocio',
            },
        ),
    ]
