# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-04 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobranza', '0005_auto_20161104_0752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuota',
            name='cuota',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True),
        ),
    ]
