# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-04 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobranza', '0007_auto_20161104_0755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuota',
            name='cuota',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
