# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-04 13:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cobranza', '0008_auto_20161104_0800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuota',
            name='lote',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='asociacion.InformacionLote'),
        ),
    ]
