# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-04 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobranza', '0009_auto_20161104_0802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rubrocobranza',
            name='fecha_fin',
        ),
        migrations.AddField(
            model_name='rubrocobranza',
            name='dias',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
