# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-04 13:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asociacion', '0003_auto_20161104_0644'),
        ('cobranza', '0010_auto_20161104_0816'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mora', models.DecimalField(decimal_places=2, max_digits=5)),
                ('lote', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='asociacion.SocioLote')),
            ],
            options={
                'verbose_name': 'Mora',
                'verbose_name_plural': 'Moras',
            },
        ),
    ]
