# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-04 13:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cobranza', '0011_mora'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mora',
            name='lote',
        ),
        migrations.DeleteModel(
            name='Mora',
        ),
    ]
